// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	net "net"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, conn
func (_m *Handler) Handle(ctx context.Context, conn net.Conn) {
	_m.Called(ctx, conn)
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - conn net.Conn
func (_e *Handler_Expecter) Handle(ctx interface{}, conn interface{}) *Handler_Handle_Call {
	return &Handler_Handle_Call{Call: _e.mock.On("Handle", ctx, conn)}
}

func (_c *Handler_Handle_Call) Run(run func(ctx context.Context, conn net.Conn)) *Handler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(net.Conn))
	})
	return _c
}

func (_c *Handler_Handle_Call) Return() *Handler_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *Handler_Handle_Call) RunAndReturn(run func(context.Context, net.Conn)) *Handler_Handle_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *Handler) Start() {
	_m.Called()
}

// Handler_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Handler_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Handler_Expecter) Start() *Handler_Start_Call {
	return &Handler_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Handler_Start_Call) Run(run func()) *Handler_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Handler_Start_Call) Return() *Handler_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *Handler_Start_Call) RunAndReturn(run func()) *Handler_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Handler) Stop() {
	_m.Called()
}

// Handler_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Handler_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Handler_Expecter) Stop() *Handler_Stop_Call {
	return &Handler_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Handler_Stop_Call) Run(run func()) *Handler_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Handler_Stop_Call) Return() *Handler_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Handler_Stop_Call) RunAndReturn(run func()) *Handler_Stop_Call {
	_c.Run(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
