// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	session "tcp-message-processor/internal/session"

	mock "github.com/stretchr/testify/mock"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// All provides a mock function with no fields
func (_m *SessionRepository) All() []*session.Session {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*session.Session
	if rf, ok := ret.Get(0).(func() []*session.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*session.Session)
		}
	}

	return r0
}

// SessionRepository_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type SessionRepository_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *SessionRepository_Expecter) All() *SessionRepository_All_Call {
	return &SessionRepository_All_Call{Call: _e.mock.On("All")}
}

func (_c *SessionRepository_All_Call) Run(run func()) *SessionRepository_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionRepository_All_Call) Return(_a0 []*session.Session) *SessionRepository_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_All_Call) RunAndReturn(run func() []*session.Session) *SessionRepository_All_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: username
func (_m *SessionRepository) Create(username string) *session.Session {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *session.Session
	if rf, ok := ret.Get(0).(func(string) *session.Session); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	return r0
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - username string
func (_e *SessionRepository_Expecter) Create(username interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", username)}
}

func (_c *SessionRepository_Create_Call) Run(run func(username string)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(_a0 *session.Session) *SessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(string) *session.Session) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: username
func (_m *SessionRepository) Find(username string) (*session.Session, bool) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *session.Session
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*session.Session, bool)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *session.Session); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SessionRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type SessionRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - username string
func (_e *SessionRepository_Expecter) Find(username interface{}) *SessionRepository_Find_Call {
	return &SessionRepository_Find_Call{Call: _e.mock.On("Find", username)}
}

func (_c *SessionRepository_Find_Call) Run(run func(username string)) *SessionRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SessionRepository_Find_Call) Return(_a0 *session.Session, _a1 bool) *SessionRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepository_Find_Call) RunAndReturn(run func(string) (*session.Session, bool)) *SessionRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
