services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: tcp_processor_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:17
    container_name: tcp_processor_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tcpuser
      POSTGRES_PASSWORD: tcppass
      POSTGRES_DB: tcpprocessor
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tcpuser"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  rabbitmq_data:
  postgres_data:
