// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	tcp "tcp-message-processor/common/pkg/tcp"

	mock "github.com/stretchr/testify/mock"
)

// Messenger is an autogenerated mock type for the Messenger type
type Messenger struct {
	mock.Mock
}

type Messenger_Expecter struct {
	mock *mock.Mock
}

func (_m *Messenger) EXPECT() *Messenger_Expecter {
	return &Messenger_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with no fields
func (_m *Messenger) Read() (tcp.Message, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 tcp.Message
	var r1 error
	if rf, ok := ret.Get(0).(func() (tcp.Message, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() tcp.Message); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tcp.Message)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Messenger_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type Messenger_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *Messenger_Expecter) Read() *Messenger_Read_Call {
	return &Messenger_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *Messenger_Read_Call) Run(run func()) *Messenger_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Messenger_Read_Call) Return(_a0 tcp.Message, _a1 error) *Messenger_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Messenger_Read_Call) RunAndReturn(run func() (tcp.Message, error)) *Messenger_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *Messenger) Write(_a0 tcp.Message) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(tcp.Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Messenger_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type Messenger_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 tcp.Message
func (_e *Messenger_Expecter) Write(_a0 interface{}) *Messenger_Write_Call {
	return &Messenger_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *Messenger_Write_Call) Run(run func(_a0 tcp.Message)) *Messenger_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tcp.Message))
	})
	return _c
}

func (_c *Messenger_Write_Call) Return(_a0 error) *Messenger_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Messenger_Write_Call) RunAndReturn(run func(tcp.Message) error) *Messenger_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessenger creates a new instance of Messenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Messenger {
	mock := &Messenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
